;;; init-cnfonts.el --- -*- lexical-binding: t -*-
;;; Info
;; Author: Chopong
;; Email : chopong@aliyun.com
;; Date  : 2019-05-21,Tue,16:26:26
;;; Commentary:

;;; Code:


;; Auto generated by cnfonts
;; <https://github.com/tumashu/cnfonts>

(use-package cnfonts :ensure t :defer t
  :config
;;  (cnfonts-enable)
  (setq cnfonts-use-face-font-rescale t))

(use-package pangu-spacing :ensure t :defer 2)

;; (set-face-attribute
;;  'default nil
;;  :font (font-spec :name "-*-Consolas-normal-normal-normal-*-*-*-*-*-m-0-iso10646-1"
;;                   :weight 'normal
;;                   :slant 'normal
;;                   :size 12.5))
;; (dolist (charset '(kana han symbol cjk-misc bopomofo))
;;   (set-fontset-font
;;    (frame-parameter nil 'font)
;;    charset
;;    (font-spec :name "-*-Microsoft YaHei-normal-normal-normal-*-*-*-*-*-p-0-iso10646-1"
;;               :weight 'normal
;;               :slant 'normal
;;               :size 15.0)))
;; (use-package pangu-spacing :ensure t :defer 2)


(provide 'init-cnfonts)
;;; init-cnfonts.el ends here
