(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(package-selected-packages
   (quote
    (ess tagedit forge yasnippet-snippets yari yard-mode yaml-mode yagist yafolding xref-js2 writeroom-mode writegood-mode window-purpose whole-line-or-region whitespace-cleanup-mode wgrep-ag weibo vlf visual-regexp use-package unicode-fonts unfill typescript-mode treemacs-projectile treemacs-magit treemacs-icons-dired toml-mode telephone-line symon symbol-overlay switch-window super-save suggest sublimity sqlformat speed-type spaceline-all-the-icons smex smart-mode-line slime-company skewer-less session scss-mode scratch sass-mode ruby-hash-syntax ruby-compilation rspec-mode robe rg restclient regex-tool rainbow-mode rainbow-delimiters projectile-rails prettier-js pomidor poly-markdown pip-requirements perspective parinfer paradox pangu-spacing ov origami org-super-agenda org-projectile org-pomodoro org-noter org-mind-map org-download org-caldav org-bullets olivetti nyan-mode nov neotree multiple-cursors mu4e-alert move-dup mode-line-bell mmm-mode magithub magit-todos list-unicode-display linum-relative leetcode keyfreq json-mode js-comint ivy-xref ipretty info-colors indent-guide immortal-scratch ibuffer-vc ibuffer-projectile hyde hungry-delete httprepl hippie-expand-slime highlight-symbol highlight-quoted highlight-parentheses highlight-indent-guides highlight-escape-sequences hackernews guide-key goto-line-preview goto-gem google-translate google-this golden-ratio gitignore-mode github-review github-clone gitconfig-mode git-timemachine git-blamed gif-screencast fullframe fountain-mode flycheck-pycheckers flycheck-pos-tip flycheck-package flycheck-color-mode-line flycheck-clojure flycheck-checkbashisms flx fireplace fill-column-indicator exwm expand-region exec-path-from-shell esup emamux elpy elisp-slime-nav elfeed-goodies elein ein ebib dumb-jump dracula-theme doom-themes disable-mouse diredfl dired-sidebar dimmer diminish diff-hl default-text-scale deadgrep dashboard dash-at-point csv-mode css-eldoc crux crontab-mode counsel company-quickhelp company-jedi company-box company-anaconda command-log-mode color-identifiers-mode coffee-mode cnfonts cmd-to-echo cljsbuild-mode cl-libify cl-lib-highlight calfw-org calfw bundler bug-reference-github browse-kill-ring browse-at-remote bm benchmark-init beacon auto-compile anzu aggressive-indent ag add-node-modules-path academic-phrases))))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
